version: '3'

services:
  frontend:
    build:
      context: ./webapp
      dockerfile: ./Dockerfile
    volumes:
      - ./webapp:/code
    # command: ash -c "npm run start"
    ports:
      - 4801:80

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - ./backend:/code
      - /code/node_moduless
    command: ash -c "python /code/manage.py collectstatic --noinput && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 4800:8000
