name: Docker-compose Actions Workflow - hackcrisis fakebusters website
# This workflow is triggered on pushes to the repository.
on: push

jobs:
  build-frontend:
    # https://help.github.com/en/articles/software-in-virtual-environments-for-github-actions#ubuntu-1804-lts
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Install dependencies
      run: cd webapp && npm install
    - name: Build
      run: cd webapp && npm run build
    # - name: Build
    #   run: npm run build -- --prod
    # - name: Test
    #   run: npm test -- --configuration=ci
    # - name: E2E
    #   run: npm run e2e -- --configuration=ci


  deploy:
    runs-on: self-hosted
    steps:
      - name: Get repo
        uses: actions/checkout@v2
      - name: Up compose
        run: docker-compose up -d --force-recreate --build