name: Docker-compose Actions Workflow - hackcrisis fakebusters website
# This workflow is triggered on pushes to the repository.
on: push

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Get repo
        uses: actions/checkout@v2
      - name: Up compose
        run: docker-compose up -d --force-recreate --build