name: Docker-compose Actions Workflow - hackcrisis fakebusters website
# This workflow is triggered on pushes to the repository.
on: push

jobs:
  build-frontend:
    # https://help.github.com/en/articles/software-in-virtual-environments-for-github-actions#ubuntu-1804-lts
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Npm install
      working-directory: ./webapp
      run: npm install
    - name: Npm build
      working-directory: ./webapp
      run: npm run build

  deploy:
    runs-on: self-hosted
    steps:
      - name: Get repo
        uses: actions/checkout@v2
      - name: Up compose
        run: docker-compose up -d --force-recreate --build